blueprint:
  name: Automation Rolladen Test
  description: |
    # Rolladen
    Automation eines Rolladen abhängig von Werktag, Uhrzeit, Fensterstellung.

    Zur Aktivierung/Deaktivierung der Steuerung kann ein globaler Schalter definiert werden. 
    Das Hoch- und Runterfahren kann durch separate Schalter unterbunden werden. 

    Die Rahmenzeiten (frühestes und spätestes Öffnen und Schließen) werden durch Zeiteinträge definiert, 
    dazwischen wird die Bewegung durch die Variable "es ist Tag" gesteuert. Diese Variable kann durch 
    eine separate Automation den eigenen Wünschen entsprechend gesetzt werden.

    Link zum Repo [Github](https://github.com/cradermacher/ha-repo/blob/main/blueprints/shutter)

    Version 1.0
    Datum 04.10.2023
  source_url: https://github.com/cradermacher/ha-repo/blob/main/blueprints/automation/shutter/shutter-short.yaml

  domain: automation
  input:
    shutter:
      name: Rolladen
      description: Zu steuernden Rolladen auswählen
      selector:
        entity:
          domain: cover
          multiple: false
    earliest_open_workday:
      name: Frühestes Öffnen an Werktagen
      selector:
        entity:
          domain: input_datetime
          multiple: false
    text_status:
      name: Statusausgabe
      description: Statusausgabe als Text, enthält die Information, was der letzte Auslöser war
      selector:
        entity:
          domain: input_text
          multiple: false
    mode:
      name: Modus
      description: Modusanzeige für den jeweiligen Rolladen (Tag/Nacht)
      selector:
        entity:
          domain: input_select
          multiple: false
          
trigger:
  - platform: time
    at: !input earliest_open_workday
    id: earliest_open_workday


action:
  ############################################
  # Tag-Werktag-früheste Öffnung
  ############################################
  - if:
      - condition: trigger
        id:
          - earliest_open_workday
    then:
      - service: cover.set_cover_position
        data:
          position: 0
        target:
          entity_id: !input shutter
      - service: input_text.set_value
        data:
          value: "Der Rolladen wurde automatisch geöffnet (früheste Öffnung)"
        target:
          entity_id: !input text_status
      - service: input_select.select_option
        data:
          option: "Tag"
        target:
          entity_id: !input mode
    alias: Tag-Werktag-früheste Öffnung
