blueprint:
  name: Automation Rolladen
  description: |
    # Rolladen
    Automation eines Rolladen abhängig von Werktag, Uhrzeit, Fensterstellung.

    Zur Aktivierung/Deaktivierung der Steuerung kann ein globaler Schalter definiert werden. 
    Das Hoch- und Runterfahren kann durch separate Schalter unterbunden werden. 

    Die Rahmenzeiten (frühestes und spätestes Öffnen und Schließen) werden durch Zeiteinträge definiert, 
    dazwischen wird die Bewegung durch die Variable "es ist Tag" gesteuert. Diese Variable kann durch 
    eine separate Automation den eigenen Wünschen entsprechend gesetzt werden.

    Link zum Repo [Github](https://github.com/cradermacher/ha-repo/blob/main/blueprints/shutter)

    Version 1.0
    Datum 04.10.2023
    source_url: https://github.com/cradermacher/ha-repo/blob/main/blueprints/automation/shutter/shutter.yaml

  domain: automation
  input:
    shutter:
      name: Rolladen
      description: Zu steuernden Rolladen auswählen
      selector:
        entity:
          domain: cover
          multiple: false
    workday:
      name: Werktag
      description: Entität die anzeigt ob ein Werktag ist
      selector:
        entity:
          domain: binary_sensor
          multiple: false
    day_night:
      name: Es ist Tag
      description: Entität die anzeigt ob es Tag oder Nacht ist
      selector:
        entity:
          domain: input_boolean
          multiple: false
    active:
      name: Aktiv
      description: Entität zur Steuerung, ob die gesamte Automation ausgeführt werden soll
      selector:
        entity:
          domain: input_boolean
          multiple: false
    close_off:
      name: Automatisch Runterfahren ausschalten
      description: Entität, die verhindert, dass der Rolladen automatisch runterfährt
      selector:
        entity:
          domain: input_boolean
          multiple: false
    open_off:
      name: Automatisch Hochfahren ausschalten
      description: Entität, die verhindert, das der Rolladen automatisch hochfährt
      selector:
        entity:
          domain: input_boolean
          multiple: false
    earliest_open_workday:
      name: Frühestes Öffnen an Werktagen
      selector:
        entity:
          domain: input_datetime
          multiple: false
    earliest_open_non_workday:
      name: Frühestes Öffnen an nicht Werktagen
      selector:
        entity:
          domain: input_datetime
          multiple: false
    latest_open_workday:
      name: Spätestes Öffnen an Werktagen
      selector:
        entity:
          domain: input_datetime
          multiple: false
    latest_open_non_workday:
      name: Spätestes Öffnen an nicht Werktagen
      selector:
        entity:
          domain: input_datetime
          multiple: false
    earliest_close_workday:
      name: Frühestes Schließen an Werktagen
      selector:
        entity:
          domain: input_datetime
          multiple: false
    earliest_close_non_workday:
      name: Frühestes Schließen an nicht Werktagen
      selector:
        entity:
          domain: input_datetime
          multiple: false
    latest_close_workday:
      name: Spätestes Schließen an Werktagen
      selector:
        entity:
          domain: input_datetime
          multiple: false
    latest_close_non_workday:
      name: Spätestes Schließen an nicht Werktagen
      selector:
        entity:
          domain: input_datetime
          multiple: false
    window_sensor:
      name: Fenstersensor
      description: Entität für die Ermittlung der Fensterstellung (offen, gekippt, geschlossen)
      selector:
        entity:
          domain: sensor
          multiple: false
    window_open_value:
      name: Rolladenstellung bei Fenster offen
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider
          step: 1.0
    window_tilted_value:
      name: Rolladenstellung bei Fenster gekippt
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider
          step: 1.0
    window_closed_value:
      name: Rolladenstellung bei Fenster geschlossen
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider
          step: 1.0
    text_status:
      name: Statusausgabe
      description: Statusausgabe als Text, enthält die Information, was der letzte Auslöser war
      selector:
        entity:
          domain: input_text
          multiple: false
    mode:
      name: Modus
      description: Modusanzeige für den jeweiligen Rolladen (Tag/Nacht)
      selector:
        entity:
          domain: input_select
          multiple: false

trigger:
  - platform: time
    at: !input earliest_open_workday
    id: earliest_open_workday

  - platform: time
    at: !input earliest_open_non_workday
    id: earliest_open_non_workday

  - platform: time
    at: !input latest_open_workday
    id: latest_open_workday

  - platform: time
    at: !input latest_open_non_workday
    id: latest_open_non_workday

  - platform: time
    at: !input earliest_close_workday
    id: earliest_close_workday

  - platform: time
    at: !input earliest_close_non_workday
    id: earliest_close_non_workday

  - platform: time
    at: !input latest_close_workday
    id: latest_close_workday

  - platform: time
    at: !input latest_close_non_workday
    id: latest_close_non_workday

  - platform: state
    entity_id: !input day_night
    from: "on"
    to: "off"
    id: night

  - platform: state
    entity_id: !input day_night
    from: "off"
    to: "on"
    id: day

  - platform: state
    entity_id: !input window_sensor
    to: "open"
    id: window_open

  - platform: state
    entity_id: !input window_sensor
    to: "tilted"
    id: window_tilted

  - platform: state
    entity_id: !input window_sensor
    to: "closed"
    id: window_closed

action:
  ############################################
  # Tag-Werktag-früheste Öffnung
  ############################################
  - if:
      - condition: trigger
        id:
          - earliest_open_workday
      - condition: state
        entity_id: !input active
        state: on
      - condition: state
        entity_id: !input workday
        state: "on"
      - condition: state
        entity_id: !input day_night
        state: "on"
      - condition: state
        entity_id: !input open_off
        state: "off"
    then:
      - service: cover.set_cover_position
        data:
          position: 0
        target:
          entity_id: !input shutter
      - service: input_text.set_value
        data:
          value: "Der Rolladen wurde automatisch geöffnet (früheste Öffnung)"
        target:
          entity_id: !input text_status
      - service: input_select.select_option
        data:
          option: "Tag"
        target:
          entity_id: !input mode
    alias: Tag-Werktag-früheste Öffnung
  
  ##############################################
  # Tag-Werktag-zwischen früheste und späteste Öffnung
  #############################################
  - if:
      - condition: trigger
        id:
          - day
      - condition: state
        entity_id: !input active
        state: on
      - condition: state
        entity_id: !input workday
        state: "on"
      - condition: time
        after: !input earliest_open_workday
        before: !input latest_open_workday
      - condition: state
        entity_id: !input open_off
        state: "off"
    then:
      - service: cover.set_cover_position
        data:
          position: 0
        target:
          entity_id: !input shutter
      - service: input_text.set_value
        data:
          value: "Der Rolladen wurde automatisch geöffnet (zwischen früheste und
            späteste Öffnung)"
        target:
          entity_id: !input text_status
      - service: input_select.select_option
        data:
          option: "Tag"
        target:
          entity_id: !input mode
    alias: Tag-Werktag-zwischen früheste und späteste Öffnung

  ##############################################
  # Tag-Werktag-späteste Öffnung
  ##############################################
  - if:
      - condition: trigger
        id:
          - latest_open_workday
      - condition: state
        entity_id: !input active
        state: on
      - condition: state
        entity_id: !input workday
        state: "on"
      - condition: state
        entity_id: !input open_off
        state: "off"
      - condition: state
        entity_id: !input mode
        state: Nacht
    then:
      - service: cover.set_cover_position
        data:
          position: 0
        target:
          entity_id: !input shutter
      - service: input_text.set_value
        data:
          value: "Der Rolladen wurde automatisch geöffnet (späteste Öffnung)"
        target:
          entity_id: !input text_status
      - service: input_select.select_option
        data:
          option: "Tag"
        target:
          entity_id: !input mode
    alias: Tag-Werktag-späteste Öffnung

  ###############################################
  # Tag-non-Werktag-früheste Öffnung
  ###############################################
  - if:
      - condition: trigger
        id:
          - earliest_open_non_workday
      - condition: state
        entity_id: !input active
        state: on
      - condition: state
        entity_id: !input workday
        state: "off"
      - condition: state
        entity_id: !input day_night
        state: "on"
      - condition: state
        entity_id: !input open_off
        state: "off"
    then:
      - service: cover.set_cover_position
        data:
          position: 0
        target:
          entity_id: !input shutter
      - service: input_text.set_value
        data:
          value: "Der Rolladen wurde automatisch geöffnet (früheste Öffnung)"
        target:
          entity_id: !input text_status
      - service: input_select.select_option
        data:
          option: "Tag"
        target:
          entity_id: !input mode
    alias: Tag-non-Werktag-früheste Öffnung

  ###################################################
  # Tag-non-Werktag-zwischen früheste und späteste Öffnung
  ###################################################
  - if:
      - condition: trigger
        id:
          - day
      - condition: state
        entity_id: !input active
        state: on
      - condition: state
        entity_id: !input workday
        state: "off"
      - condition: time
        after: !input earliest_open_non_workday
        before: !input latest_open_non_workday
      - condition: state
        entity_id: !input open_off
        state: "off"
    then:
      - service: cover.set_cover_position
        data:
          position: 0
        target:
          entity_id: !input shutter
      - service: input_text.set_value
        data:
          value: "Der Rolladen wurde automatisch geöffnet (zwischen früheste und späteste Öffnung)"
        target:
          entity_id: !input text_status
      - service: input_select.select_option
        data:
          option: "Tag"
        target:
          entity_id: !input mode
    alias: Tag-non-Werktag-zwischen früheste und späteste Öffnung

  ##################################################
  #  Tag-non-Werktag-späteste Öffnung
  ##################################################
  - if:
      - condition: trigger
        id:
          - latest_open_non_workday
      - condition: state
        entity_id: !input active
        state: on
      - condition: state
        entity_id: !input workday
        state: "off"
      - condition: state
        entity_id: !input open_off
        state: "off"
      - condition: state
        entity_id: !input mode
        state: Nacht
    then:
      - service: cover.set_cover_position
        data:
          position: 0
        target:
          entity_id: !input shutter
      - service: input_text.set_value
        data:
          value: "Der Rolladen wurde automatisch geöffnet (späteste Öffnung)"
        target:
          entity_id: !input text_status
      - service: input_select.select_option
        data:
          option: "Tag"
        target:
          entity_id: !input mode
    alias: Tag-non-Werktag-späteste Öffnung